{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "RANDOM_SEED = 42"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 各パス指定"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = 'model/keypoint_classifier/keypoint.csv'\n",
    "model_save_path = 'model/keypoint_classifier/keypoint_classifier.hdf5'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 分類数設定"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "NUM_CLASSES = 4"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 学習データ読み込み"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_dataset = np.loadtxt(dataset, delimiter=',', dtype='float32', usecols=list(range(1, (21 * 2) + 1)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "y_dataset = np.loadtxt(dataset, delimiter=',', dtype='int32', usecols=(0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X_dataset, y_dataset, train_size=0.75, random_state=RANDOM_SEED)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# モデル構築"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-03-17 11:44:35.806279: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    }
   ],
   "source": [
    "model = tf.keras.models.Sequential([\n",
    "    tf.keras.layers.Input((21 * 2, )),\n",
    "    tf.keras.layers.Dropout(0.2),\n",
    "    tf.keras.layers.Dense(20, activation='relu'),\n",
    "    tf.keras.layers.Dropout(0.4),\n",
    "    tf.keras.layers.Dense(10, activation='relu'),\n",
    "    tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " dropout (Dropout)           (None, 42)                0         \n",
      "                                                                 \n",
      " dense (Dense)               (None, 20)                860       \n",
      "                                                                 \n",
      " dropout_1 (Dropout)         (None, 20)                0         \n",
      "                                                                 \n",
      " dense_1 (Dense)             (None, 10)                210       \n",
      "                                                                 \n",
      " dense_2 (Dense)             (None, 4)                 44        \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 1,114\n",
      "Trainable params: 1,114\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model.summary()  # tf.keras.utils.plot_model(model, show_shapes=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# モデルチェックポイントのコールバック\n",
    "cp_callback = tf.keras.callbacks.ModelCheckpoint(\n",
    "    model_save_path, verbose=1, save_weights_only=False)\n",
    "# 早期打ち切り用コールバック\n",
    "es_callback = tf.keras.callbacks.EarlyStopping(patience=20, verbose=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# モデルコンパイル\n",
    "model.compile(\n",
    "    optimizer='adam',\n",
    "    loss='sparse_categorical_crossentropy',\n",
    "    metrics=['accuracy']\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# モデル訓練"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/1000\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-03-17 11:44:45.454220: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 4).  Label values: 0 1 1 0 2 0 1 2 0 3 2 2 1 2 2 2 1 2 0 1 0 0 2 0 0 1 0 1 2 2 0 0 0 0 1 1 0 0 1 1 0 2 0 1 1 1 2 2 0 0 1 3 1 2 2 2 0 0 3 1 1 0 0 0 0 4 1 2 0 1 0 2 0 3 1 3 1 2 2 0 2 2 0 1 2 0 2 2 0 1 1 2 0 0 2 1 1 1 2 2 2 1 0 0 2 3 3 2 0 1 1 0 2 0 0 0 0 1 1 0 1 3 1 1 4 2 0 2\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n      app.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/2889966517.py\", line 1, in <module>\n      model.fit(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 245, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 1862, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/backend.py\", line 5202, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 4).  Label values: 0 1 1 0 2 0 1 2 0 3 2 2 1 2 2 2 1 2 0 1 0 0 2 0 0 1 0 1 2 2 0 0 0 0 1 1 0 0 1 1 0 2 0 1 1 1 2 2 0 0 1 3 1 2 2 2 0 0 3 1 1 0 0 0 0 4 1 2 0 1 0 2 0 3 1 3 1 2 2 0 2 2 0 1 2 0 2 2 0 1 1 2 0 0 2 1 1 1 2 2 2 1 0 0 2 3 3 2 0 1 1 0 2 0 0 0 0 1 1 0 1 3 1 1 4 2 0 2\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_715]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/2889966517.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m model.fit(\n\u001b[0m\u001b[1;32m      2\u001b[0m     \u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m     \u001b[0my_train\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1000\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0mbatch_size\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m128\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n      app.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/2889966517.py\", line 1, in <module>\n      model.fit(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 245, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 1862, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/backend.py\", line 5202, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 4).  Label values: 0 1 1 0 2 0 1 2 0 3 2 2 1 2 2 2 1 2 0 1 0 0 2 0 0 1 0 1 2 2 0 0 0 0 1 1 0 0 1 1 0 2 0 1 1 1 2 2 0 0 1 3 1 2 2 2 0 0 3 1 1 0 0 0 0 4 1 2 0 1 0 2 0 3 1 3 1 2 2 0 2 2 0 1 2 0 2 2 0 1 1 2 0 0 2 1 1 1 2 2 2 1 0 0 2 3 3 2 0 1 1 0 2 0 0 0 0 1 1 0 1 3 1 1 4 2 0 2\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_715]"
     ]
    }
   ],
   "source": [
    "model.fit(\n",
    "    X_train,\n",
    "    y_train,\n",
    "    epochs=1000,\n",
    "    batch_size=128,\n",
    "    validation_data=(X_test, y_test),\n",
    "    callbacks=[cp_callback, es_callback]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-03-17 11:45:20.552267: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 4).  Label values: 3 0 0 2 3 0 0 0 1 1 1 1 2 0 2 0 0 0 1 1 4 0 3 0 1 2 0 0 0 0 0 0 0 2 0 2 2 2 0 3 2 0 1 0 2 1 1 2 1 0 0 0 1 0 1 0 2 0 2 2 3 0 2 1 2 0 2 2 2 1 0 1 2 0 2 2 4 0 1 0 0 2 3 1 2 0 1 2 0 0 1 2 1 1 0 2 0 0 0 3 2 2 1 0 1 4 1 2 2 0 2 2 2 0 1 0 1 0 1 2 0 1 2 1 1 4 1 0\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n      app.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/575961420.py\", line 2, in <module>\n      val_loss, val_acc = model.evaluate(X_test, y_test, batch_size=128)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1716, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1525, in test_function\n      return step_function(self, iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1514, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1507, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1473, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 245, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 1862, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/backend.py\", line 5202, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 4).  Label values: 3 0 0 2 3 0 0 0 1 1 1 1 2 0 2 0 0 0 1 1 4 0 3 0 1 2 0 0 0 0 0 0 0 2 0 2 2 2 0 3 2 0 1 0 2 1 1 2 1 0 0 0 1 0 1 0 2 0 2 2 3 0 2 1 2 0 2 2 2 1 0 1 2 0 2 2 4 0 1 0 0 2 3 1 2 0 1 2 0 0 1 2 1 1 0 2 0 0 0 3 2 2 1 0 1 4 1 2 2 0 2 2 2 0 1 0 1 0 1 2 0 1 2 1 1 4 1 0\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_test_function_891]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/575961420.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# モデル評価\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mval_loss\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mval_acc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mevaluate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_test\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_test\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m128\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 54\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     55\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n      app.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n      await self.process_one()\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 446, in process_one\n      await dispatch(*args)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n      await result\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n      reply_content = await reply_content\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n      result = self._run_cell(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n      return runner(coro)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/ipykernel_88210/575961420.py\", line 2, in <module>\n      val_loss, val_acc = model.evaluate(X_test, y_test, batch_size=128)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1716, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1525, in test_function\n      return step_function(self, iterator)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1514, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1507, in run_step\n      outputs = model.test_step(data)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1473, in test_step\n      self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 245, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py\", line 1862, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/keras/backend.py\", line 5202, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 4).  Label values: 3 0 0 2 3 0 0 0 1 1 1 1 2 0 2 0 0 0 1 1 4 0 3 0 1 2 0 0 0 0 0 0 0 2 0 2 2 2 0 3 2 0 1 0 2 1 1 2 1 0 0 0 1 0 1 0 2 0 2 2 3 0 2 1 2 0 2 2 2 1 0 1 2 0 2 2 4 0 1 0 0 2 3 1 2 0 1 2 0 0 1 2 1 1 0 2 0 0 0 3 2 2 1 0 1 4 1 2 2 0 2 2 2 0 1 0 1 0 1 2 0 1 2 1 1 4 1 0\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_test_function_891]"
     ]
    }
   ],
   "source": [
    "# モデル評価\n",
    "val_loss, val_acc = model.evaluate(X_test, y_test, batch_size=128)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "# 保存したモデルのロード\n",
    "model = tf.keras.models.load_model(model_save_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0.22370693 0.19891818 0.33915192 0.23822293]\n",
      "2\n"
     ]
    }
   ],
   "source": [
    "# 推論テスト\n",
    "predict_result = model.predict(np.array([X_test[0]]))\n",
    "print(np.squeeze(predict_result))\n",
    "print(np.argmax(np.squeeze(predict_result)))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 混同行列"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZUAAAFlCAYAAAAjyXUiAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAApIElEQVR4nO3deZyVdfn/8dc1C5u4gMgyMxQoVC4lFKB9USJJwA3UEnHXUKygNMl+YlpmUVaCaS6FgaKBMrmxuoUSobKZpCwiazDDwLC4QQozc67fH3McjwZniLnPuW/u8376uB9zzn3Ofe7rw3HONdfnuu/7mLsjIiIShLywAxARkfhQUhERkcAoqYiISGCUVEREJDBKKiIiEhglFRERCUxBpnfQqHFJzh6z3Pmw4rBDCMVr8+8JO4TQHPyFc8IOIRQ1iUTYIYSmene5BfVaVVvXNPjzsrDVkYHFsz8ynlRERGQfJWrCjqDBlFRERKLCD/yKT0lFRCQqYjCNqEa9iIgERpWKiEhEuKa/REQkMDGY/lJSERGJihhUKuqpiIhIYJRURESiIlHT8CUNM2tiZgvM7F9mttTMfp5cf4uZlZvZ4uRyeso2I81slZmtMLN+9Q1B018iIlGR+emvXcAp7r7DzAqBuWb2dPKxO9z99tQnm9kxwGDgWKAI+JuZfc7d95q9lFRERKIiw416r/2q3x3Ju4XJJd2lYQYCj7r7LmCtma0CegCv7G0DTX+JiESEe6LBi5kNNbNFKcvQ1H2YWb6ZLQYqgefdfX7yoeFm9rqZjTezFsl1xcCGlM3Lkuv2SklFRCRG3H2su3dLWcZ+6vEad+8ClAA9zOw44D7gKKALUAGMTj59TxenTHvRSyUVEZGoSCQavuwjd38HmA30d/fNyWSTAO6ndooLaiuT9imblQAb072ukoqISFR4ouFLGmZ2hJkdlrzdFPgG8KaZtUt52jnAkuTtqcBgM2tsZh2BzsCCdPtQo15EJCoyf+n7dsAEM8untqgodffpZvawmXWhdmprHXA1gLsvNbNSYBlQDQxLd+QXKKmIiERHhg8pdvfXga57WH9Jmm1GAaP2dR+a/hIRkcCoUhERiQpdUFJERAITgwtKKqmIiERFDCoV9VRERCQwqlRERCKinqN1DwhKKiIiUaGeioiIBCYGPRUlFRGRqIhBpaJGvYiIBCaWlUrjxo15YdbjNG7ciIKCfJ54Yia3/mJ0/RsewPLy8ih97kE2b9rCsItHcOhhh3D72F9S3L6I8g0bGXHVT3jv3ffDDrPBdu3ezeUjfsHuqmpqamo49eQeDLv0W9z78OM8/vSLtDj0YAB+cMX59OrRhZdffYPfj3+UqupqCgsKGHHVhZzQ5diQRxG8FSteZsf7O6mpqaG6uob/63lG2CFlRb++vRkz5lby8/IY/8Aj/PZ394QdUsNk/tpfGRfLpLJr1y769hvEzp3/oaCggNkvPskzz77IggX/DDu0jLnkqvNZs3IdBx18EABXfv9S5v9jEX/+w0Nc+f1LufL7lzLmlwf4LxzQqLCQcb/9Cc2aNqGquprLrruVk7ofD8Al55zG5ed98sO0xaEHc/etP6L14S1YuW4D37nxN8yadHcYoWdc336D2Lbt7bDDyJq8vDzuunMU/U+/gLKyCua9MpNp059j+fKVYYe2/zT9FV07d/4HgMLCAgoLC6j9Fs14atOuNb1O7cnjE6fUrft6/148NXkGAE9NnsEpp30trPACZWY0a9oEgOrqGqprajDb0/cI1Tq6UwdaH177JXadPlvCrt1V7N5dlZVYJbN6dO/K6tXrWLt2PVVVVZSWTmHAWf3CDqthsvh9KplSb1Ixsy+Y2f8zs7vM7M7k7aOzEVxD5OXlsXDBs5SX/YtZs/7BwoWvhR1Sxtzwix8y+ta7SSQ+TpyHH9GSrZXbANhauY2WrVrsbfMDTk1Ngm99dyRfO/+7nNj1OL70hU4APDLtOc79zg3cPHos776/87+2e37uAr5w1Gdp1Kgw2yFnnjszpk/klZdnMGTIhWFHkxVFxW3ZUPbx90WVlVdQVNQ2xIgCkOHvU8mGtEnFzP4f8Ci1Xym5AFiYvP2Imd2QZru670hO1Pz3L3c2JBIJuvfoR8cju9OtWxeOPebzocSRaV87tSfbt25n2etvhh1K1uTn5/HYfb/mbxP/wJIVq1m5bgODzvwGMx+4g8fu/RVHtDyM28dO/MQ2q9aVcce4R/nZNUNCijqzen/9XE786ukMGHgp37n6Mk466YSwQ8q4PVWocZ6ROFDU11MZAhzr7p+YLzCzMcBS4LY9bZT8TuSxAI0al4T6Lr/77nvMmfMKffv1ZumyFWGGkhFdexxP7369OLnP/9G4SWMOan4Qt91zC9u2bKdV68PZWrmNVq0PZ/vW+M21H9L8ILoffzQvLXz9E72Ub572dYb/9Pa6+5u2bOPaW+/gV9d/h/ZFbcIINeMqKjYDsGXLNqZMfYbu3bowd+78kKPKrPKyCtqXFNXdLyluV/fvcMCKwPRVQ9U3/ZUAivawvl3ysUhq1aolhx56CABNmjThlFNOYsWKVSFHlRm/H3UvfbqeRd/u5/Cjq29i/kuLuGHYLbz47D84+/zaD9qzzz+DF5+ZE3Kkwdj+znu8t6O2+v1w127m/XMpHdu3Y0tKg3rWy4vo1KEEgPd27GTYzbdzzRXn0/XYeFarzZo1pXnzg+puf6NPL5Yujd8fUJ+2cNFiOnXqSIcO7SksLGTQoIFMm/5c2GE1TAx6KvVVKtcCs8xsJbAhue4zQCdgeAbjapB2bdswbtwd5Ofnk5dnPPbYdGbOnBV2WFn15z9MYMz9v+LcCwdQUb6J6668MeyQArFl+zvcdPsfqUkk8ITTt9cJfO3ELzPyt/fy5up/Y2YUtzmCn/7g2wA8MvU5NmzczJ8mPcmfJj0JwJ9+fQOHH3ZomMMIVJs2R1A6+X4ACgryeXTyFJ57fna4QWVBTU0N11x7EzNnTCI/L48HJ0xm2bK3wg6rQeJw7S+rbw7SzPKAHkAxtf2UMmBhfd9T/JGwp7/C1Pmw4rBDCMVr8w/8Q5f318FfOCfsEEJRE4G/kMNSvbt874cf/o8+mPNggz8vm/a6PLB49ke956m4ewKYl4VYRERyWwyScyxPfhQROSBF4JDghlJSERGJClUqIiISmBhUKrG9TIuIiGSfKhURkajQ9JeIiAQmBtNfSioiIlERg0pFPRUREQmMKhURkaiIQaWipCIiEhXqqYiISGBUqYiISGBiUKmoUS8iIoFRpSIiEhWa/hIRkcDEYPpLSUVEJCpiUKmopyIiEhUZ/o56M2tiZgvM7F9mttTMfp5c39LMnjezlcmfLVK2GWlmq8xshZn1q28ISioiIrljF3CKux8PdAH6m9mJwA3ALHfvDMxK3sfMjgEGA8cC/YF7zSw/3Q6UVEREosK94Uval3d39x3Ju4XJxYGBwITk+gnA2cnbA4FH3X2Xu68FVgE90u1DSUVEJCoCmP4ys6FmtihlGZq6CzPLN7PFQCXwvLvPB9q4ewVA8mfr5NOLgQ0pm5cl1+2VGvUiIlERQKPe3ccCY9M8XgN0MbPDgCfN7Lg0L2d7eol0+1elIiKSg9z9HWA2tb2SzWbWDiD5szL5tDKgfcpmJcDGdK+rpCIiEhWeaPiShpkdkaxQMLOmwDeAN4GpwGXJp10GTEnengoMNrPGZtYR6AwsSLcPTX+JiERF5s9TaQdMSB7BlQeUuvt0M3sFKDWzIcB64DwAd19qZqXAMqAaGJacPtsrJRURkaio5+ithr+8vw503cP6bUCfvWwzChi1r/tQUhERiQqdUS8iIvIxVSoZtPrdirBDCIU1bxl2CKEpzMvNX6maxO6wQ4iHGFQqufkbICISRbpKsYiIBMUTmW3UZ4OSiohIVMRg+kuNehERCYwqFRGRqFBPRUREAqOeioiIBEY9FRERkY+pUhERiYoYVCpKKiIiUZHhC0pmg5KKiEhUqFIREZHAxODoLzXqRUQkMKpURESiQic/iohIYGIw/aWkIiISEa5GvYiIBCYGlYoa9SIiEhhVKiIiUaFGvYiIBCYG019KKiIiURGDRr16KiIiEhhVKiIiUaHpLxERCYwa9SIiEhhVKiIiEpQ4nFGvRr2IiAQm1kklLy+PBfOf4cknHww7lKzp3PlI5s9/um6prFzK8OFDwg4rMLt27Wbwlddw7mXfY+BFV3P3nx+ue2ziX6dw5uArGXjR1Yy+Z9wntqvYVEn3b5zDA5Mey3bIGXHvH3/D2nULWbDwmbp1LVocytRpD7P49ReYOu1hDjvskBAjzI5+fXuzdMkc3lw2lx9fPyzscBou4Q1fQhbr6a/vf38Ib765ioMPaR52KFmzcuUaTjjhNKA2qa5Zs4CpU5+pZ6sDR6NGhYy/6zaaNWtKVXU1l373R5x8Yjd27drNi3Pn8cRD99KoUSO2vf3OJ7b7zV1jOfnEbuEEnQETH36cP/3xIe6/f3TduutGfJfZs19izOg/ct2I73DdiO/y05t/E2KUmZWXl8ddd46i/+kXUFZWwbxXZjJt+nMsX74y7ND2XwSSQkPFtlIpLm7Haaf1YfwDk8IOJTSnnNKTtWvXs359edihBMbMaNasKQDV1dVUV1djZkx+agZDLh5Eo0aNADi8xWF128ya8zIlRW05quNnwwg5I156aQFvb3/nE+vOOPNUJk58HICJEx/nzLP6hhBZ9vTo3pXVq9exdu16qqqqKC2dwoCz+oUdVsN4ouFLyGKbVEbffgsjR44iEYPMv7/OO28AkydPCTuMwNXU1PDNy4bR68wL+Gr3rnzp2C+wbn05r/5rCRdcdS2XD7ueN5avAOA/H3zI+L/8le99+6KQo8681q1bsXnTFgA2b9rCEUccHnJEmVVU3JYNZRvr7peVV1BU1DbEiAIQg+mv/U4qZnZFmseGmtkiM1uUqNm5v7vYb6ef3ofKLVt57bU3sr7vqCgsLOSMM07liSdmhB1K4PLz83l8wj3MevJh3lj2FivXrKOmpob33t/BpLF3MGLYlfzo5l/j7twz7mEuOf+cuupG4sPM/mude/gfqrmuIT2VnwMP7OkBdx8LjAVo1Lgk6+/y/321O2ee0Zf+/U6hSZPGHHLIwTz4wF1cfsUPsh1KaPr1683ixUuorNwadigZc8jBzen+5S8xd94i2rRuxTe+1hMz44vHfB4z4+133uWNpSt4/sW5jLl3HO/v2ImZ0bhRIy781oCwww9cZeVW2rQ9gs2bttCm7RFs2bIt7JAyqrysgvYlRXX3S4rbUVGxOcSIGs4zXGmYWXvgIaAtkADGuvudZnYLcBWwJfnUG919ZnKbkcAQoAb4gbs/m24faZOKmb2+t4eANvs4jqy76ebbuOnm2wDo1eur/PCHV+dUQgEYNGggpaXxm/ra/vY7FBQUcMjBzflw1y7mLXyNb198Hs2aNmXBq4vp8eUvsW59GVXV1bQ47FAeuu/2um3vGfcXmjVtEsuEAjBzxt+46KJvMmb0H7noom8yY/rzYYeUUQsXLaZTp4506NCe8vJNDBo0kEsuPcCPAMv89FU1MMLd/2lmBwOvmtlH/6Pc4e63pz7ZzI4BBgPHAkXA38zsc+5es7cd1FeptAH6AW9/ar0BL+/7OCSbmjZtQp8+JzN8+MiwQwnclm1v85Nf3k5NIoEnnH6nnEzvnidQVVXFTb+6g7Mv/g6FhQX86qYRe5weiYsHHryTk3udyOGHt2DFypcZ9cvfM2b0fTz08N1cetkgyjZs5JKLD/AP2HrU1NRwzbU3MXPGJPLz8nhwwmSWLXsr7LAaJsMnP7p7BVCRvP2+mS0HitNsMhB41N13AWvNbBXQA3hlbxtYujlIMxsHPODuc/fw2CR3v7C+QYQx/RUVeRbb4yDSer9sdtghhKbFZ/qEHUIoPqzeHXYIoaneXR7YXy/vDz+9wZ+XB989c5/iMbMOwBzgOOA64HLgPWARtdXM22Z2NzDP3f+S3GYc8LS77/WEr7Sfeu4+ZE8JJflYvQlFRET+BwEc/ZV6oFRyGfrp3ZhZc+Bx4Fp3fw+4DzgK6EJtJfPRCVB7SlBpE1+sT34UETmgBNBTST1Qak/MrJDahDLR3Z9IbrM55fH7genJu2VA+5TNS4CNpJGb8zMiIhHk7g1e0rHaRuM4YLm7j0lZ3y7laecAS5K3pwKDzayxmXUEOgML0u1DlYqISFRk/uivnsAlwBtmtji57kbgAjPrQu3U1jrgagB3X2pmpcAyao8cG5buyC9QUhERyRnJHvme+iQz02wzChi1r/tQUhERiYoIXGaloZRUREQiItNn1GeDkoqISFQoqYiISGDCv3J9g+mQYhERCYwqFRGRiFBPRUREgqOkIiIigVFPRURE5GOqVEREIkI9FRERCU4Mpr+UVEREIkKVioiIBCcGlYoa9SIiEhhVKiIiEeExqFSUVEREokJJRUREgqJKRUREghODpKJGvYiIBEaViohIRGj6S0REAqOkIiIigYlDUlFPRUREApPxSiXPcjdvtWp2SNghhKJ63lNhhxCaD6t3hx2CHMjcwo6gwTT9JSISEXGY/lJSERGJCE+oUhERkYDEoVLJ3YaHiIgETpWKiEhEuBr1IiISlDhMfympiIhERBwa9eqpiIhIYFSpiIhEhHvYETSckoqISETEYfpLSUVEJCKUVEREJDBxmP5So15EJEeYWXsze9HMlpvZUjO7Jrm+pZk9b2Yrkz9bpGwz0sxWmdkKM+tX3z6UVEREIsIT1uClHtXACHc/GjgRGGZmxwA3ALPcvTMwK3mf5GODgWOB/sC9ZpafbgdKKiIiEeFuDV7Sv75XuPs/k7ffB5YDxcBAYELyaROAs5O3BwKPuvsud18LrAJ6pNuHeioiIhGRzTPqzawD0BWYD7Rx9wqoTTxm1jr5tGJgXspmZcl1e6WkIiISEYkArv1lZkOBoSmrxrr72E89pznwOHCtu79nttf97umBtIcTKKmIiMRIMoGM3dvjZlZIbUKZ6O5PJFdvNrN2ySqlHVCZXF8GtE/ZvATYmG7/6qmIiEREpnsqVluSjAOWu/uYlIemApclb18GTElZP9jMGptZR6AzsCDdPlSpiIhERBZOfuwJXAK8YWaLk+tuBG4DSs1sCLAeOA/A3ZeaWSmwjNojx4a5e026HSipiIhERKZPfnT3uey5TwLQZy/bjAJG7es+NP0lIiKBUaUiIhIRuvaXiIgEJohDisOmpCIiEhH6jnoREQmMrlIsIiKSIpZJpXPnI5k//+m6pbJyKcOHDwk7rIxoV9yW0injeXHeVGa9/BRDrr647rErrrqQv8+fxqyXn+Int1wXYpTB2VVVzUW/f4JBt/+Vc39byr3PLATguX+t5tzfltL1R39i6YYtdc9/Z+eHXHnvNL46chy/fmJuWGFnVL++vVm6ZA5vLpvLj68fFnY4WRW3sSfcGryELZbTXytXruGEE04DIC8vjzVrFjB16jMhR5UZNdXV3Hrz71jy+nIOat6Mp18oZc7slzniiMPpe9rXOfXkc9m9u4rDW7UMO9RANCrI5/7vnkWzxoVU1dRwxd1TOenoz9CpbUvGXN6XXzw25xPPb1yQz7D+3Vi16W1WbdoeUtSZk5eXx113jqL/6RdQVlbBvFdmMm36cyxfvjLs0DIujmOPQ08llpVKqlNO6cnatetZv7487FAyonLzVpa8vhyAnTv+w8q31tC2XRsu+fb53HPnOHbvrgJg29Z4fKCaGc0aFwJQXZOguiaBAUe2aUGH1of91/ObNi6k65HtaFSQ9isgDlg9undl9ep1rF27nqqqKkpLpzDgrHq/RykW4jh294YvYas3qZjZF8ysT/Kqlqnr+2curOCcd94AJk+eUv8TY6CkfRHHfeloXnv1dY48qgMnfPUrTHt+Eo9Ne4Djux4XdniBqUkkGDT6MU752UOc+LlivvjZNmGHFJqi4rZsKPv4+n5l5RUUFbUNMaLsiePY4zD9lTapmNkPqL2w2PeBJWY2MOXhX2UysCAUFhZyxhmn8sQTM8IOJeOaHdSUsRPu4JYbf8OO93eSX5DPoYcewlmnXsgvfzaa+8bfHnaIgcnPy6N0xLd49qcXs2T9FlZVxKMK2x97umS5R+HP1SzI5bFHWX09lauAr7j7juQXujxmZh3c/U72fv2YT1zPv6CgBfn5zff21Izq1683ixcvobJyayj7z5aCggLGTvg9Tz42g6en/w2ATRs3191e/M8lJBJOy8NbsH3b22GGGqhDmjam21HteOnNDXRqF4+e0f+qvKyC9iVFdfdLittRUbE5xIiyJ45jz4WeSr677wBw93VAb+A0MxtDmqTi7mPdvZu7dwsroQAMGjSQ0tL4T33dftetrHprDfff+1DdumdmvEDPXrXf+tnxqM/SqFFhLBLK9h0f8N4HuwD4sKqa+SvL6djmsHCDCtHCRYvp1KkjHTq0p7CwkEGDBjJt+nNhh5UVcRx7HKa/6qtUNplZF3dfDJCsWM4ExgNfzHRwDdG0aRP69DmZ4cNHhh1KRnU/oSvfGjyA5Uvf4tm/PwbAb35xJ5MnPsHoP/ySv730JFW7q7j2ezeGHGkwtr73H25+5EUS7iTc6Xv8UfQ65rO88MZabnvyJd7e8QHf//PTfL7ocO67+gwATvvlRHZ+WEVVTQ0vLlnHfUPP4Ki2LUIeSTBqamq45tqbmDljEvl5eTw4YTLLlr0VdlhZEcexx2HyztLNQZpZCVDt7pv28FhPd3+pvh00afKZOPw77ZdWzQ4JO4RQrHzo22GHEJqDzx0ddgiSZdW7ywMrD+YVndvgz8sTNz4RarmStlJx97I0j9WbUEREZN9FYfqqoWJ58qOIyIEoDo16JRURkYhIhB1AAJRUREQiwvd+UO0BI/aXaRERkexRpSIiEhGJGBwrq6QiIhIRiRhMfympiIhERBx6KkoqIiIREYejv9SoFxGRwKhSERGJCE1/iYhIYOIw/aWkIiISEXFIKuqpiIhIYFSpiIhEhHoqIiISmMSBn1OUVEREokJn1IuISGBicOkvNepFRCQ4qlRERCIiDocUK6mIiEREwg78noqmv0REIsIDWOpjZuPNrNLMlqSsu8XMys1scXI5PeWxkWa2ysxWmFm/+l5flYqISERkafrrQeBu4KFPrb/D3W9PXWFmxwCDgWOBIuBvZvY5d6/Z24urUhERySHuPgfYvo9PHwg86u673H0tsArokW4DJRURkYhIWMMXMxtqZotSlqH7uPvhZvZ6cnqsRXJdMbAh5TllyXV7paQiIhIRCazBi7uPdfduKcvYfdj1fcBRQBegAhidXL+nIwfStm7UUxERiYiwTn50980f3Taz+4HpybtlQPuUp5YAG9O9lioVEZEcZ2btUu6eA3x0ZNhUYLCZNTazjkBnYEG618p4pVKd2OtBArG3acfbYYcQikHfeyHsEEQOSNm4oKSZPQL0BlqZWRnwM6C3mXWhtlhaB1wN4O5LzawUWAZUA8PSHfkFmv4SEYmMbBxS7O4X7GH1uDTPHwWM2tfXV1IREYmIOFxQUklFRCQi4vB9KmrUi4hIYFSpiIhEhK5SLCIigVFSERGRwHgMeipKKiIiERGHSkWNehERCYwqFRGRiIhDpaKkIiISETr5UUREAqOTH0VERFKoUhERiQj1VEREJDBKKiIiEhg16kVEJDBq1IuIiKRQpSIiEhHqqYiISGDUUxERkcAkYpBW1FMREZHAqFIREYkI9VRERCQwB/7kl5KKiEhkqFIREZHA6ORHERGRFKpUREQiQocUR1i/vr1ZumQOby6by4+vHxZ2OFmTS+MuPrKYO5++q26ZvLSUAUMGcNGIi7nr2T9w59N3cetfbqVlm5Zhh5pRufSef1rcxu4BLGEz98yGUdCoOOvjzMvLY/nSf9D/9AsoK6tg3iszufiS77F8+cpsh5JVURn3aW27ZnV/UDv2BxdMYMTA69jx7g4+2PEBAGddcRbtO3+Ge2+8JytxPL3ptazs5yNRec/DEJWxV+8uD6wTMrLDhQ3+vPz1ukmhdmZiWan06N6V1avXsXbteqqqqigtncKAs/qFHVbG5eq4AY7veTwV6yvYUr6lLqEANG7WhEz/4RSmXH7P4zj2BN7gJWz1JhUz62Fm3ZO3jzGz68zs9MyHtv+KituyoWxj3f2y8gqKitqGGFF25Oq4AU4e0Is5U+bU3b/k+ksYP+8Bep/dm4mj/xJiZJmVy+95Lo89ytImFTP7GXAXcJ+Z/Rq4G2gO3GBmP0mz3VAzW2RmixKJnYEGvC/M/rv6i/Nfqx/J1XEXFBZwwqk9eGnG3Lp1D//uYb594hXMfmo2Z15+ZojRZVauvucQz7HHoadSX6XyLaAn0AsYBpzt7rcC/YDz97aRu491927u3i0v76DAgt1X5WUVtC8pqrtfUtyOiorNWY8j23J13F/p/RVWL1nNO1vf+a/H/v7UbP7vtJ7ZDypLcvU9h3iOPRHAErb6kkq1u9e4+3+A1e7+HoC7f0A04t+jhYsW06lTRzp0aE9hYSGDBg1k2vTnwg4r43J13L0Gfo2/p0x9tevw8QfNCaeeQNnqsjDCyopcfc8hnmOPQ0+lvvNUdptZs2RS+cpHK83sUCKcVGpqarjm2puYOWMS+Xl5PDhhMsuWvRV2WBmXi+Nu3KQxXU7uwj0j765bd/kNl1F8VAmJRIIt5Vu4Z2R2jvwKQy6+5x/J5bFHWdpDis2ssbvv2sP6VkA7d3+jvh2EcUixhCuMQ4qjItuHFEv4gjyk+IcdBjf48/KOdY9G95DiPSWU5Pqt+5JQRERk32Wjp2Jm482s0syWpKxraWbPm9nK5M8WKY+NNLNVZrbCzOo9ZjuW56mIiByIPID/9sGDQP9PrbsBmOXunYFZyfuY2THAYODY5Db3mll+uhdXUhERiYhsVCruPgfY/qnVA4EJydsTgLNT1j/q7rvcfS2wCuiR7vWVVEREYiT1PMHkMnQfNmvj7hUAyZ+tk+uLgQ0pzytLrtsrXaVYRCQigjgk2N3HAmMbHg0Ae2r6pw1SlYqISESEeEb9ZjNrB5D8WZlcXwa0T3leCbCRNJRUREQiIsSTH6cClyVvXwZMSVk/2Mwam1lHoDOwIN0LafpLRCQisnFGuZk9AvQGWplZGfAz4Dag1MyGAOuB8wDcfamZlQLLgGpgmLvXpHt9JRURkRzi7hfs5aE+e3n+KGDUvr6+koqISETs43kmkaakIiISEZG9oOL/QElFRCQi4lCp6OgvEREJjCoVEZGI0PSXiIgEJnGAfx0yKKmIiETGgZ9SlFRERCIjCl8H3FBq1IuISGBUqYiIREQcDilWUhERiQgd/SUiIoGJQ09FSUVEJCLiMP2lRr2IiARGlYqISESopyIiIoFxnVEvIiJBiUOjXj0VEREJjCoVEZGIUE9FZA/eT3wYdggiB6Q4HFKspCIiEhFx6KkoqYiIREQcjv5So15ERAKjSkVEJCLUqBcRkcCoUS8iIoFRo15ERAKjRr2IiEgKVSoiIhGh6S8REQmMGvUiIhKYhHoqIiIiH1OlIiISEQd+naKkIiISGWrUi4hIYJRUREQkMHE4+VFJRUQkh5jZOuB9oAaodvduZtYSmAx0ANYBg9z97f15fR39JSISEQm8wcs++rq7d3H3bsn7NwCz3L0zMCt5f78oqYiIRIQH8N9+GghMSN6eAJy9vy+kpCIiEhHu3uDFzIaa2aKUZeindwM8Z2avpjzWxt0rkjFUAK33dwzqqYiIREQQR3+5+1hgbJqn9HT3jWbWGnjezN5s8E5TqFIREckh7r4x+bMSeBLoAWw2s3YAyZ+V+/v6SioiIhERxPRXOmZ2kJkd/NFtoC+wBJgKXJZ82mXAlP0dg6a/REQiIgsnP7YBnjQzqP38n+Tuz5jZQqDUzIYA64Hz9ncHSioiIhGR6Uvfu/sa4Pg9rN8G9AliH5r+EhGRwKhSERGJCH2fSoT169ubpUvm8Oayufz4+mFhh5M1uTbu5occxM//9FMemj2eCS+O45gvH83XzujFA7P+zAvrn+PzX/pc2CFmXK6956niNvYQT34MTCyTSl5eHnfdOYozz7qYLx7/dc4//2yOPrpz2GFlXC6Oe/jPh7Fg9kIu7f1thvS9mvWr1rN2xTp+etUtvD7/jbDDy7hcfM8/EsexJ9wbvIQtlkmlR/eurF69jrVr11NVVUVp6RQGnNUv7LAyLtfG3ax5M44/4YvMeORpAKqrqtnx3k7Wr1rPhjVlIUeXHbn2nqeK49hzslIxs4cyEUiQiorbsqFsY939svIKiorahhhRduTauIs+0453tr/LDWOu5/5n/sj1v7uOJk2bhB1WVuXae54ql8ceZWmTiplN/dQyDTj3o/tptqu79kwisTPwoOuTPAb7E+LwPQX1ybVx5xfk87njOjPl4Wlc1f87fPCfD7lw2OCww8qqXHvPU8Vx7HGY/qrv6K8SYBnwZ2ovQmZAN2B0uo1Srz1T0Kg466MsL6ugfUlR3f2S4nZUVGzOdhhZl2vj3lKxhS0VW1j+Wu2li/4+Yw4XDrsg5KiyK9fe81RxHHsUpq8aqr7pr27Aq8BPgHfdfTbwgbv/3d3/nung9tfCRYvp1KkjHTq0p7CwkEGDBjJt+nNhh5VxuTbu7VvepnLjFtofWQLAV076Mv9e+e+Qo8quXHvPU8Vx7LGvVNw9AdxhZn9N/txc3zZRUFNTwzXX3sTMGZPIz8vjwQmTWbbsrbDDyrhcHPddN9/NTX8YSUGjQir+XcFtI37HSf17cs0vhnNoy0P59YRRrFq6mh9fvN/fORRpufiefySOY49DpWL/yxykmZ1B7WWTb9zXbcKY/pJwndT66LBDCM3cyuVhhyBZVr27/L+bO/vpyFZdG/x5uWbra4HFsz/+p6rD3WcAMzIUi4hITqudHDqwRX4qS0QkV2ThKsUZp6QiIhIRB/oh0RDTM+pFRCQcqlRERCJC018iIhKYOEx/KamIiEREFE5ebCglFRGRiIjDyY9q1IuISGBUqYiIRIR6KiIiEhgd/SUiIoGJQ6WinoqIiARGlYqISETokGIREQlMHKa/lFRERCJCjXoREQlMHCoVNepFRCQwqlRERCJCjXoREQlMHK79paQiIhIRqlRERCQwatSLiIikUKUiIhIRceipqFIREYkId2/wUh8z629mK8xslZndEPQYVKmIiEREpnsqZpYP3AOcCpQBC81sqrsvC2ofqlRERHJHD2CVu69x993Ao8DAIHegpCIiEhEewFKPYmBDyv2y5LrAZHz6q3p3uWV6H3tjZkPdfWxY+w9Tro49V8cNuTv2OI07iM9LMxsKDE1ZNTbl32dPrx/onFvcK5Wh9T8ltnJ17Lk6bsjdsefquPfI3ce6e7eUJTXhlgHtU+6XABuD3H/ck4qIiHxsIdDZzDqaWSNgMDA1yB3o6C8RkRzh7tVmNhx4FsgHxrv70iD3EfekEot51v2Uq2PP1XFD7o49V8e9X9x9JjAzU69vcbjWjIiIRIN6KiIiEpjYJpVMX4ogqsxsvJlVmtmSsGPJJjNrb2YvmtlyM1tqZteEHVM2mFkTM1tgZv9KjvvnYceUbWaWb2avmdn0sGORmCaVlEsRnAYcA1xgZseEG1XWPAj0DzuIEFQDI9z9aOBEYFiOvOe7gFPc/XigC9DfzE4MN6SsuwZYHnYQUiuWSYUsXIogqtx9DrA97Diyzd0r3P2fydvvU/shE+iZwlHktXYk7xYml5xplJpZCXAG8OewY5FacU0qGb8UgUSXmXUAugLzQw4lK5LTP4uBSuB5d8+JcSf9HvgxkAg5DkmKa1LJ+KUIJJrMrDnwOHCtu78XdjzZ4O417t6F2rOje5jZcSGHlBVmdiZQ6e6vhh2LfCyuSSXjlyKQ6DGzQmoTykR3fyLseLLN3d8BZpM7PbWewAAzW0ftFPcpZvaXcEOSuCaVjF+KQKLFzAwYByx39zFhx5MtZnaEmR2WvN0U+AbwZqhBZYm7j3T3EnfvQO3v+AvufnHIYeW8WCYVd68GProUwXKgNOhLEUSVmT0CvAJ83szKzGxI2DFlSU/gEmr/Wl2cXE4PO6gsaAe8aGavU/vH1PPurkNrJTQ6o15ERAITy0pFRETCoaQiIiKBUVIREZHAKKmIiEhglFRERCQwSioiIhIYJRUREQmMkoqIiATm/wOQl0XWTC0l5AAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 504x432 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Classification Report\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.21      0.01      0.01       400\n",
      "           1       0.10      0.02      0.03       385\n",
      "           2       0.27      0.90      0.41       344\n",
      "           3       0.00      0.00      0.00        73\n",
      "           4       0.00      0.00      0.00        61\n",
      "\n",
      "    accuracy                           0.25      1263\n",
      "   macro avg       0.12      0.19      0.09      1263\n",
      "weighted avg       0.17      0.25      0.13      1263\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n",
      "/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n",
      "/Users/brownia1/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n",
      "  _warn_prf(average, modifier, msg_start, len(result))\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "\n",
    "def print_confusion_matrix(y_true, y_pred, report=True):\n",
    "    labels = sorted(list(set(y_true)))\n",
    "    cmx_data = confusion_matrix(y_true, y_pred, labels=labels)\n",
    "    \n",
    "    df_cmx = pd.DataFrame(cmx_data, index=labels, columns=labels)\n",
    " \n",
    "    fig, ax = plt.subplots(figsize=(7, 6))\n",
    "    sns.heatmap(df_cmx, annot=True, fmt='g' ,square=False)\n",
    "    ax.set_ylim(len(set(y_true)), 0)\n",
    "    plt.show()\n",
    "    \n",
    "    if report:\n",
    "        print('Classification Report')\n",
    "        print(classification_report(y_test, y_pred))\n",
    "\n",
    "Y_pred = model.predict(X_test)\n",
    "y_pred = np.argmax(Y_pred, axis=1)\n",
    "\n",
    "print_confusion_matrix(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tensorflow-Lite用のモデルへ変換"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n"
     ]
    }
   ],
   "source": [
    "# 推論専用のモデルとして保存\n",
    "model.save(model_save_path, include_optimizer=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-03-17 11:45:45.497521: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Assets written to: /var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/tmpu2zx2_5p/assets\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded\n",
      "2022-03-17 11:45:46.351793: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:357] Ignored output_format.\n",
      "2022-03-17 11:45:46.351805: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored drop_control_dependency.\n",
      "2022-03-17 11:45:46.352406: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/tmpu2zx2_5p\n",
      "2022-03-17 11:45:46.353585: I tensorflow/cc/saved_model/reader.cc:78] Reading meta graph with tags { serve }\n",
      "2022-03-17 11:45:46.353596: I tensorflow/cc/saved_model/reader.cc:119] Reading SavedModel debug info (if present) from: /var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/tmpu2zx2_5p\n",
      "2022-03-17 11:45:46.358150: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.\n",
      "2022-03-17 11:45:46.377513: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: /var/folders/1g/z0p4n10x0x1crx0r9v9tk2q00000gn/T/tmpu2zx2_5p\n",
      "2022-03-17 11:45:46.387370: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 34966 microseconds.\n",
      "2022-03-17 11:45:46.403886: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.\n",
      "2022-03-17 11:45:46.432428: I tensorflow/lite/tools/optimize/quantize_weights.cc:225] Skipping quantization of tensor sequential/dense/MatMul because it has fewer than 1024 elements (840).\n",
      "2022-03-17 11:45:46.432440: I tensorflow/lite/tools/optimize/quantize_weights.cc:225] Skipping quantization of tensor sequential/dense_1/MatMul because it has fewer than 1024 elements (200).\n",
      "2022-03-17 11:45:46.432445: I tensorflow/lite/tools/optimize/quantize_weights.cc:225] Skipping quantization of tensor sequential/dense_2/MatMul because it has fewer than 1024 elements (40).\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "6416"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# モデルを変換(量子化)\n",
    "tflite_save_path = 'model/keypoint_classifier/keypoint_classifier.tflite'\n",
    "\n",
    "converter = tf.lite.TFLiteConverter.from_keras_model(model)\n",
    "converter.optimizations = [tf.lite.Optimize.DEFAULT]\n",
    "tflite_quantized_model = converter.convert()\n",
    "\n",
    "open(tflite_save_path, 'wb').write(tflite_quantized_model)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 推論テスト"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "interpreter = tf.lite.Interpreter(model_path=tflite_save_path)\n",
    "interpreter.allocate_tensors()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 入出力テンソルを取得\n",
    "input_details = interpreter.get_input_details()\n",
    "output_details = interpreter.get_output_details()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "interpreter.set_tensor(input_details[0]['index'], np.array([X_test[0]]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 361 µs, sys: 254 µs, total: 615 µs\n",
      "Wall time: 459 µs\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "# 推論実施\n",
    "interpreter.invoke()\n",
    "tflite_results = interpreter.get_tensor(output_details[0]['index'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0.22370693 0.1989182  0.33915192 0.23822288]\n",
      "2\n"
     ]
    }
   ],
   "source": [
    "print(np.squeeze(tflite_results))\n",
    "print(np.argmax(np.squeeze(tflite_results)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
